GET http://localhost:5000/db/users

###

GET http://localhost:5000/db/steps

###

POST http://localhost:5000/db/users
Content-Type: application/json

{
    "name": "Tibor",
    "email": "tibi@gmail.com",
    "passwd": "t"
}

### 
GET http://localhost:5000/db/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MjEsIm5hbWUiOiJUaWJvciIsImVtYWlsIjoidGliaUBnbWFpbC5jb20iLCJpYXQiOjE3MDEyNDY4OTgsImV4cCI6MTcwMTMzMzI5OH0.tjMXf43As0JwueTjbkWS_r8ylgxSAYfyTA_j4V529gM
###

POST http://localhost:5000/email/send
Content-Type: application/json

{
    "to": "walkowiczszasa@turr.hu",
    "subject": "teszt email",
    "message": "<h1>Helló</h1><hr><h6>Szása<>"
}

###

POST http://localhost:5000/db/logincheck
Content-Type: application/json

{
    "email": "nagyhazi.szabolcs@gmail.com",
    "passwd": "5ea345ab330cf29f81d8de9bf5466f508fe351e1"
}


### 

GET http://localhost:5000/db/permissioncheck
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MywibmFtZSI6IkFkbWluIiwiZW1haWwiOiJuYWd5aGF6aS5zemFib2xjc0BnbWFpbC5jb20iLCJyaWdodHMiOiJhZG1pbmlzenRyw6F0b3IiLCJpYXQiOjE3MDE2NzkxMDAsImV4cCI6MTcwMTc2NTUwMH0.UZT9LHfJT9T9C7Kjz_9nNLlJ-lJWt70xO8tfjVzdjl8

###

POST http://localhost:5000/db/emailcheck
Content-Type:  application/json

{
    "email": "belaaaa@gmail.com"
}